
GET http://localhost:8001/params/1?nom=hola
Accept-Language: cristino

### //POST CREA / PUT MODIFICA


GET http://localhost:8001/params/2?nom=adios
Accept-Language: es-es
Accept: text/xml

###

GET http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json

###

POST http://localhost:8010/actores/
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
    "id":203,
    "nombre":"Nuevo",
    "apellidos":"actor"
}

###
get http://localhost:8010/categorias
Accept: text/xml

###
get http://localhost:8010/actores
Accept: text/xml

###
get http://localhost:8010/peliculas
Accept: text/xml

###
get http://localhost:8010/lenguajes
Accept: text/xml

###
get http://localhost:8010/actores/1
Accept: text/xml


###

put http://localhost:8010/actores/200
Content-Type: application/json

{
  "id": 200,
  "nombre": "CARMELO",
  "apellidos": "COTON"
}

###
post http://localhost:8010/actores/500
Content-Type: application/json

{
  "id":500,
  "nombre": "eqeqeq",
  "apellidos": "coton"
}


###

put http://localhost:8010/lenguajes/2
Content-Type: application/json
  
{
  "languageId": 2,
  "nombre": "italiano"
}

###
post http://localhost:8010/lenguajes
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
  "languageId":6,
  "lastUpdate":null,
  "nombre": "italianoo"
}
###
post http://localhost:8010/peliculas
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
  "id":1001,
  "title":"NUEVAAAAAA",
  "description": "A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies",
  "idioma":{
      "languageId": 1,
      "lastUpdate": "2006-02-15",
      "name": "English"
  }

}

###
post http://localhost:8010/categorias
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
  "id":6,
  "Categoria":"NuevaCategoria"
}

###

put http://localhost:8010/categorias/5
Content-Type: application/json

{
  "id": 5,
  "Categoria": "Animacion"
}
###
delete http://localhost:8001/actores/206

###
delete http://localhost:8010/lenguajes/6

###
get http://localhost:8001/auto/countries

###

POST http://localhost:8001/auto/countries
Content-Type: application/json

{
    "countryId":110,
    "country": "ESPAÑA"
}

